<?php
/**
 * AirVolume
 *
 * PHP version 5
 *
 * @category Class
 * @package  Crhg\RemoClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Crhg\RemoClient\Model;
use \Crhg\RemoClient\ObjectSerializer;

/**
 * AirVolume Class Doc Comment
 *
 * @category Class
 * @description Empty means automatic. Numbers express the amount of volume. The range of AirVolumes which the air conditioner accepts depends on the air conditioner model and operation mode. Check the &#39;AirConRangeMode&#39; information in the response for the range of the particular air conditioner model and operation mode.
 * @package  Crhg\RemoClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AirVolume
{
    /**
     * Possible values of this enum
     */
    const EMPTY = '';
    const AUTO = 'auto';
    const _1 = '1';
    const _2 = '2';
    const _3 = '3';
    const _4 = '4';
    const _5 = '5';
    const _6 = '6';
    const _7 = '7';
    const _8 = '8';
    const _9 = '9';
    const _10 = '10';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EMPTY,
            self::AUTO,
            self::_1,
            self::_2,
            self::_3,
            self::_4,
            self::_5,
            self::_6,
            self::_7,
            self::_8,
            self::_9,
            self::_10,
        ];
    }
}


