<?php
/**
 * OperationMode
 *
 * PHP version 5
 *
 * @category Class
 * @package  Crhg\RemoClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Crhg\RemoClient\Model;
use \Crhg\RemoClient\ObjectSerializer;

/**
 * OperationMode Class Doc Comment
 *
 * @category Class
 * @description The range of OperationModes which the air conditioner accepts depends on the air conditioner model. Check the &#39;AirConRangeMode&#39; information in the response for the range of the particular air conditioner model.
 * @package  Crhg\RemoClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OperationMode
{
    /**
     * Possible values of this enum
     */
    const EMPTY = '';
    const COOL = 'cool';
    const WARM = 'warm';
    const DRY = 'dry';
    const BLOW = 'blow';
    const AUTO = 'auto';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EMPTY,
            self::COOL,
            self::WARM,
            self::DRY,
            self::BLOW,
            self::AUTO,
        ];
    }
}


