<?php
/**
 * AirConRangeModesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Crhg\RemoClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Crhg\RemoClient;

/**
 * AirConRangeModesTest Class Doc Comment
 *
 * @category    Class */
// * @description AirConRangeModes
/**
 * @package     Crhg\RemoClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AirConRangeModesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AirConRangeModes"
     */
    public function testAirConRangeModes()
    {
    }

    /**
     * Test attribute "cool"
     */
    public function testPropertyCool()
    {
    }

    /**
     * Test attribute "warm"
     */
    public function testPropertyWarm()
    {
    }

    /**
     * Test attribute "dry"
     */
    public function testPropertyDry()
    {
    }

    /**
     * Test attribute "blow"
     */
    public function testPropertyBlow()
    {
    }

    /**
     * Test attribute "auto"
     */
    public function testPropertyAuto()
    {
    }
}
