<?php
/**
 * AirConRangeModeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Crhg\RemoClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Crhg\RemoClient;

/**
 * AirConRangeModeTest Class Doc Comment
 *
 * @category    Class */
// * @description AirConRangeMode
/**
 * @package     Crhg\RemoClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AirConRangeModeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AirConRangeMode"
     */
    public function testAirConRangeMode()
    {
    }

    /**
     * Test attribute "temp"
     */
    public function testPropertyTemp()
    {
    }

    /**
     * Test attribute "vol"
     */
    public function testPropertyVol()
    {
    }

    /**
     * Test attribute "dir"
     */
    public function testPropertyDir()
    {
    }
}
