<?php
/**
 * ApplianceTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Crhg\RemoClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Crhg\RemoClient;

/**
 * ApplianceTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description Type of the appliance. \&quot;AC\&quot; (Air conditioner) is 1st class citizen appliance, which is included in our IRDB (InfraRed signals DataBase). The \&quot;ApplianceModel\&quot; stores meta data about the appliance. We provide AC specific UI. Everything else is \&quot;IR\&quot;. We just learn the signals from the remote and store them, and when users tap the button on the smartphone app, our server sends it through Remo.
/**
 * @package     Crhg\RemoClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApplianceTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApplianceType"
     */
    public function testApplianceType()
    {
    }
}
