<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Crhg\RemoClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Crhg\RemoClient;

use \Crhg\RemoClient\Configuration;
use \Crhg\RemoClient\ApiException;
use \Crhg\RemoClient\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Crhg\RemoClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for applianceOrdersPost
     *
     * .
     *
     */
    public function testApplianceOrdersPost()
    {
    }

    /**
     * Test case for appliancesApplianceAirconSettingsPost
     *
     * .
     *
     */
    public function testAppliancesApplianceAirconSettingsPost()
    {
    }

    /**
     * Test case for appliancesApplianceDeletePost
     *
     * .
     *
     */
    public function testAppliancesApplianceDeletePost()
    {
    }

    /**
     * Test case for appliancesAppliancePost
     *
     * .
     *
     */
    public function testAppliancesAppliancePost()
    {
    }

    /**
     * Test case for appliancesApplianceSignalOrdersPost
     *
     * .
     *
     */
    public function testAppliancesApplianceSignalOrdersPost()
    {
    }

    /**
     * Test case for appliancesApplianceSignalsGet
     *
     * .
     *
     */
    public function testAppliancesApplianceSignalsGet()
    {
    }

    /**
     * Test case for appliancesApplianceSignalsPost
     *
     * .
     *
     */
    public function testAppliancesApplianceSignalsPost()
    {
    }

    /**
     * Test case for appliancesGet
     *
     * .
     *
     */
    public function testAppliancesGet()
    {
    }

    /**
     * Test case for appliancesPost
     *
     * .
     *
     */
    public function testAppliancesPost()
    {
    }

    /**
     * Test case for detectappliancePost
     *
     * .
     *
     */
    public function testDetectappliancePost()
    {
    }

    /**
     * Test case for devicesDeviceDeletePost
     *
     * .
     *
     */
    public function testDevicesDeviceDeletePost()
    {
    }

    /**
     * Test case for devicesDeviceHumidityOffsetPost
     *
     * .
     *
     */
    public function testDevicesDeviceHumidityOffsetPost()
    {
    }

    /**
     * Test case for devicesDevicePost
     *
     * .
     *
     */
    public function testDevicesDevicePost()
    {
    }

    /**
     * Test case for devicesDeviceTemperatureOffsetPost
     *
     * .
     *
     */
    public function testDevicesDeviceTemperatureOffsetPost()
    {
    }

    /**
     * Test case for devicesGet
     *
     * .
     *
     */
    public function testDevicesGet()
    {
    }

    /**
     * Test case for signalsSignalDeletePost
     *
     * .
     *
     */
    public function testSignalsSignalDeletePost()
    {
    }

    /**
     * Test case for signalsSignalPost
     *
     * .
     *
     */
    public function testSignalsSignalPost()
    {
    }

    /**
     * Test case for signalsSignalSendPost
     *
     * .
     *
     */
    public function testSignalsSignalSendPost()
    {
    }

    /**
     * Test case for usersMeGet
     *
     * .
     *
     */
    public function testUsersMeGet()
    {
    }

    /**
     * Test case for usersMePost
     *
     * .
     *
     */
    public function testUsersMePost()
    {
    }
}
